### ISSUE TITLE
How to upload to album

### ISSUE THREAD

**Issue by MakawaMT** [AKiniyalocts/imgur-android#13]
Anonymous uploads are working but how do I upload to an album that is on my account?

**Comment by AKiniyalocts** [comment]
You'll need to obtain a access token for your account via OAuth2, that process is explained here: [https://api.imgur.com/oauth2](https://api.imgur.com/oauth2)

Then, following [imgur's api documentation](https://api.imgur.com/endpoints/image), you will upload that image adding an `album_id` parameter onto the request. Hint: Checkout the "Image Upload" section.

**Comment by MakawaMT** [comment]
thanks.
but that still requires the user to accept authentication page and I was trying to avoid that since it's my account

**Comment by AKiniyalocts** [comment]
Oh I see, so you're looking to automate that authentication process since it's only going to authenticate your personal imgur account. In that case you *could* obtain that access code via OAuth and then simply store it in your application. This can be unsafe, and could compromise your imgur account if it is accessed.

From there, all you really need to worry about on your client would be grabbing a `refresh_token` when you need it. Again, imgur has some awesome documentation for that process here: https://api.imgur.com/oauth2
