### ISSUE TITLE
Issue with albumID

### ISSUE THREAD

**Issue by cooperkong** [AKiniyalocts/imgur-android#2]
Hi, 
Thanks for the great sample project.

Just a quick question, I haven't seen you using albumId in the application. I have tried myself and always getting "You are not the owner of album 'xyz', which means you can't add images to it". Do you have any clue on what's the cause of it?
Is it related to using OAuth?

Thanks!

**Comment by AKiniyalocts** [comment]
@cooperkong You're exactly right. In order to upload a photo to an album on imgur, you must be the owner of that album. With the current sample, we currently do not have access to any album information because we are not authenticating with imgur (our upload is completely anonymous). I suggest opening a new issue on this project adding OAuth support. Once I have some time, I'll add it!

**Comment by cooperkong** [comment]
Hi @AKiniyalocts 
I just did a quick experiment, it seems like sending album id in the image upload API doesn't add the image into the album. However , I had to use https://api.imgur.com/3/album/{album}/add API to add image to my album after the upload call.
And of course we need to get the access_token. 

Cheers,

**Comment by AKiniyalocts** [comment]
@cooperkong interesting. I'll look into this...

In the meantime, I've created a new repo for an actual imgur library for android: https://github.com/AKiniyalocts/imgur-api

Very very early still, but I plan on devoting some time to it.
